//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Episodes
    {
        public int Id { get; set; }
        public string name3 { get; set; }
        public string noEpisode { get; set; }
        public int epRating { get; set; }
        public string epReview { get; set; }
    }
}
